name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  package-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-and-install-bun
      - name: Package JSON
        run: bun sort-package-json:check

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-and-install-bun
      - name: Prettier
        run: bun prettier:check

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-and-install-bun
      - name: Lint
        run: bun lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-and-install-bun
      - name: Type Check
        run: bun typecheck
